### ISSUE TITLE
Balance Board is identified as MotionPlus

### ISSUE THREAD

**Issue by tuomasjjrasanen** [abstrakraft/cwiid#2]
Balance Board is identified as MotionPlus, because only one byte of the whole 6 bite long extension identifier is considered. Balance Board was working before MotionPlus-support, but because both extensions report 0x4 in 0xA400FE, Balance Board was incorrectly interpreted as MotionPlus.

See http://wiibrew.org/wiki/Wiimote#The_New_Way for more information on identifying extensions.

I have fixed the issue in my fork of the repository: http://github.com/tuos/cwiid

**Comment by kuzniarpawel** [comment]
I installed cwiid from tuos latest git repository with patch to properly discover wii balance board, but wmgui crashes after trying to connect with a board.

**Comment by tuomasjjrasanen** [comment]
I'll try to remember to test this on the weekend. I've no interest on wmgui or other tools whatsoever, just libcwiid and it's python-wrapper, so I haven't test it before. I'll fix it if I can find the bug, a patch is also very welcome :-).

**Comment by tuomasjjrasanen** [comment]
I tested, but I could not be able to reproduce the behavior you described. If the problem persist, please describe the exact steps to reproduce it or error message if there is one.

As a side note, wmgui is not very useful with the board because, it only has one led which is controllable with the wmgui-program. :-) There should be balance board -specific panel, but no one has coded it yet, apparently there's really no need. As far as I am know, wmgui is intended to be just a simple app to display that the libcwiid actually works.

**Comment by kuzniarpawel** [comment]
Strange, need to make some additional tests. Previously it crashed after following sequence.
I open wmgui. Select File->Connect->I put board in discoverable mode->Press OK.
After couple of seconds it crashes.

I tried in gdb. And it worked. Now works properly. 
I'll keep you posted.

**Comment by kuzniarpawel** [comment]
Oh, I forgot it used to crash with Segmentation fault.

**Comment by abstrakraft** [comment]
tuos' patches have been applied

**Comment by kuzniarpawel** [comment]
thx
